name: user_repository
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  chopper: ^4.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0  
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.8
  chopper_generator: ^4.0.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  lint: ^1.8.2

flutter:

