include: package:lint/analysis_options.yaml

linter:

  rules:
    prefer_single_quotes: true


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore