name: orange_gorest
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  chopper: ^4.0.5
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  user_repository:
    path: ./packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  freezed: ^1.1.1
  lint: ^1.8.2
  

flutter:

  uses-material-design: true
  assets:
    - assets/ca/lets-encrypt-r3.pem