name: gorest_repository
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.5
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  freezed: ^1.1.1
  chopper_generator: ^4.0.5
  lint: ^1.8.2
  
flutter:

